// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h"

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;
            return true;
        }
    }
    return false;
}

// This is the function that the enclave will call back into to
// print a message.
void host_helloworld()
{
    fprintf(stdout, "Enclave called into host to print: Hello World!\n");
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Create the enclave
    result = oe_create_helloworld_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_helloworld_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Call into the enclave
    result = enclave_helloworld(enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    ret = 0;


    printf("Welcome to the Intel-SGX Password Manager\n");
    printf("Type \"help\"\n");

    while (true)
    {
        char strCommand[100];

        char str1[100];
        char str2[100];
        char str3[100];
        char str4[100];
        int i;
        void *encrypt = malloc(100);

        printf("Enter a command: ");

        // std::getline (std::cin, command);

        scanf("%[^\n]%*c", strCommand);
        char* split = strtok(strCommand, " ");
        strcpy(str1, split);

        if (strcmp(str1, "help") == 0) {
            printf("Example Usage\n");
            printf("create MasterPassword\n");
            printf("add Website WebsitePassword\n");
            printf("get Website MasterPassword\n");
            printf("quit\n");

        } 
        else if (strcmp(str1, "quit") == 0) 
        {
            break;
        } 
        else if (strcmp(str1, "create") == 0)
        {

            printf("Creating Password Manager\n");
            split = strtok(NULL, " ");
            strcpy(str2, split);


            //str2 = main keystore password
            int create_keystore_return;
            oe_result_t result_create;

            // Call into the enclave
            result_create = enclave_create_keystore(enclave, str2);
            if (result != OE_OK)
            {
                fprintf(
                    stderr,
                    "calling into enclave_create_keystore failed: result=%u (%s)\n",
                    result,
                    oe_result_str(result));
                goto exit;
            }

        }

    }

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
